/**
 * Evalanche Error types and codes.
 */

export enum EvalancheErrorCode {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  INVALID_PARAMS = 'INVALID_PARAMS',
  INVALID_CONFIG = 'INVALID_CONFIG',
  SIGNER_NOT_FOUND = 'SIGNER_NOT_FOUND',
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
  NETWORK_ERROR = 'NETWORK_ERROR',
  WALLET_ERROR = 'WALLET_ERROR',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  CONTRACT_CALL_FAILED = 'CONTRACT_CALL_FAILED',
  CONTRACT_NOT_DEPLOYED = 'CONTRACT_NOT_DEPLOYED',
  QUOTE_FAILED = 'QUOTE_FAILED',
  SWAP_FAILED = 'SWAP_FAILED',
  INSUFFICIENT_LIQUIDITY = 'INSUFFICIENT_LIQUIDITY',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  ARENA_SWAP_FAILED = 'ARENA_SWAP_FAILED',
  ARENA_TOKEN_NOT_FOUND = 'ARENA_TOKEN_NOT_FOUND',
  BRIDGE_FAILED = 'BRIDGE_FAILED',
  BRIDGE_QUOTE_FAILED = 'BRIDGE_QUOTE_FAILED',
  BRIDGE_EXECUTION_FAILED = 'BRIDGE_EXECUTION_FAILED',
  TRANSFER_FAILED = 'TRANSFER_FAILED',
  CROSS_CHAIN_ERROR = 'CROSS_CHAIN_ERROR',
  XCHAIN_ERROR = 'XCHAIN_ERROR',
  PCHAIN_ERROR = 'PCHAIN_ERROR',
  STAKING_ERROR = 'STAKING_ERROR',
  STAKE_POOL_INSUFFICIENT = 'STAKE_POOL_INSUFFICIENT',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  X402_PAYMENT_FAILED = 'X402_PAYMENT_FAILED',
  X402_PAYMENT_EXCEEDED = 'X402_PAYMENT_EXCEEDED',
  RPC_ERROR = 'RPC_ERROR',
  TIMEOUT = 'TIMEOUT',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  SIMULATION_FAILED = 'SIMULATION_FAILED',
  DISCOVERY_ERROR = 'DISCOVERY_ERROR',
  NEGOTIATION_ERROR = 'NEGOTIATION_ERROR',
  SETTLEMENT_ERROR = 'SETTLEMENT_ERROR',
  MEMORY_ERROR = 'MEMORY_ERROR',
  ESCROW_ERROR = 'ESCROW_ERROR',
  IDENTITY_RESOLUTION_FAILED = 'IDENTITY_RESOLUTION_FAILED',
  IDENTITY_RESOLUTION_ERROR = 'IDENTITY_RESOLUTION_ERROR',
  UNSUPPORTED_URI_SCHEME = 'UNSUPPORTED_URI_SCHEME',
  AGENT_NOT_FOUND = 'AGENT_NOT_FOUND',
  REPUTATION_SUBMIT_FAILED = 'REPUTATION_SUBMIT_FAILED',
  PLATFORM_CLI_NOT_FOUND = 'PLATFORM_CLI_NOT_FOUND',
  PLATFORM_CLI_ERROR = 'PLATFORM_CLI_ERROR',
  DYDX_ERROR = 'DYDX_ERROR',
  PERPS_ERROR = 'PERPS_ERROR',
  GAS_ZIP_ERROR = 'GAS_ZIP_ERROR',
  LIFI_API_ERROR = 'LIFI_API_ERROR',
  LIFI_STATUS_ERROR = 'LIFI_STATUS_ERROR',
  LIFI_SWAP_FAILED = 'LIFI_SWAP_FAILED',
  LIFI_TOKEN_ERROR = 'LIFI_TOKEN_ERROR',
  VAULT_ERROR = 'VAULT_ERROR',
  INTEROP_ADDRESS_ERROR = 'INTEROP_ADDRESS_ERROR',
  DAPP_RESOLUTION_ERROR = 'DAPP_RESOLUTION_ERROR',
  A2A_ERROR = 'A2A_ERROR',
  A2A_TASK_FAILED = 'A2A_TASK_FAILED',
}

export class EvalancheError extends Error {
  code: EvalancheErrorCode;
  underlying?: Error;

  constructor(message: string, code: EvalancheErrorCode = EvalancheErrorCode.UNKNOWN_ERROR, underlying?: Error) {
    super(message);
    this.name = 'EvalancheError';
    this.code = code;
    this.underlying = underlying;

    if (underlying) {
      this.stack = underlying.stack;
    }
  }

  toString(): string {
    return `[${this.code}] ${this.message}`;
  }
}
